### PR TITLE
incorporate community mission statement

### PR DESCRIPTION
**Pull request by oraNod**
issue #370

### CODE REVIEW

**Review by tiyiprh — APPROVED** [review]
Looks good to me!

**Review by tiyiprh — CHANGES_REQUESTED** [review]
Sorry @oraNod actually have some minor changes!

**Comment by tiyiprh** [comment]
- What if we put the mission statement first in the community section and then the icons under it? 
- Can we make the text have the same width as the icon section?
- We could also move the subtext that's right under "Community" currently to the beginning of the icon section
- We add a line separator between the two that doesn't span the full width

Let me know what you think!

Screenshot 2024-01-17 at 12 00 58 PM

**Comment by oraNod** [comment]
@tiyiprh Thanks for that suggestion but I'm not sure about it tbh. I think we're using a whole lot of horizontal rules elsewhere and I would prefer not to have them all over the place.

What do you think if we create an "Ansible community mission" as a secondary page under resources? I'm starting to lean towards that because we could make it really simple and have it just in markdown. A distinct page for the mission statement might also make it seem a bit more authoritative or something - and we could link to it from the footer.

**Comment by tiyiprh** [comment]
Thanks for the feedback! What if we created an "About" page and put the mission there along with the "Contact us" page? I feel like those two items could go together.

**Comment by oraNod** [comment]
> Thanks for the feedback! What if we created an "About" page and put the mission there along with the "Contact us" page? I feel like those two items could go together.

@tiyiprh Perhaps they could go together but I think a dedicated "Community mission statement" page would be better. Combining it with the contact page might make the mission statement less prominent and somewhat trivial.

@Andersson007 What do you think?

**Comment by Andersson007** [comment]
> > Thanks for the feedback! What if we created an "About" page and put the mission there along with the "Contact us" page? I feel like those two items could go together.
> 
> @tiyiprh Perhaps they could go together but I think a dedicated "Community mission statement" page would be better. Combining it with the contact page might make the mission statement less prominent and somewhat trivial.
> 
> @Andersson007 What do you think?

@oraNod , 100% agreed

**Comment by tiyiprh** [comment]
> > Thanks for the feedback! What if we created an "About" page and put the mission there along with the "Contact us" page? I feel like those two items could go together.
> 
> @tiyiprh Perhaps they could go together but I think a dedicated "Community mission statement" page would be better. Combining it with the contact page might make the mission statement less prominent and somewhat trivial.
> 
> @Andersson007 What do you think?

Sounds good!

**Comment by oraNod** [comment]
I've created a new page for the mission statement, please take a look.

**Comment by oraNod** [comment]
> Since this is the mission page, we figured it could be a little different from the rest of the pages and be a little more "fun." Here is what I've mocked up so far.
> 
>     * Added a banner to the title and made the text bigger
> 
>     * Made the text of the body bigger as well and bolded some areas
> 
>     * Threw in some of the community logos with picket signs reiterating some of the bolded words that describe Ansible and its mission
> 
> 
> Let me know your thoughts!
> 
> Mission Page

I think that looks great!

**Comment by tiyiprh** [comment]
Awesome! Here is an updated screenshot and the ansibulls as an svg. Let me know if they work properly.
Mission Page
Mission Page Galaxy
Mission Page Builder
Mission Page Ansibull

**Comment by Andersson007** [comment]
LGTM

**Comment by oraNod** [comment]
@Andersson007 and @tiyiprh Thanks for the input. I've made the changes and think the mission statement page looks really great now.

**Comment by tiyiprh** [comment]
Awesome!! I think there are some issues when viewing on mobile though, not sure if I should create a separate issue for that.

**Comment by oraNod** [comment]
@tiyiprh what issues are you seeing?

**Comment by tiyiprh** [comment]
This is what it looks like when I try to open it on mobile. It also seems like the logos don't show up on mobile.
IMG_8282

**Comment by oraNod** [comment]
Hmm, yeah. Let me see if that issue is related to this PR. Thanks for spotting it.

I added a breakpoint so the images don't display at 990px and lower: https://github.com/ansible-community/community-website/pull/380/files#diff-07c42833a7a585cc012fb704f3eee1a46a0d7bd4458a4a34286c62fde589693cR28

**Comment by oraNod** [comment]
@tiyiprh Hi. Yes, that mobile issue was a problem with this PR. Great catch! It should be fixed now if you could please take another look.

**Comment by tiyiprh** [comment]
@oraNod that looks a lot better! There does seem to be some horizontal scrolling though and the logos are still missing.
IMG_8283

**Comment by oraNod** [comment]
Thanks again @tiyiprh could you check again?

In an earlier comment I mentioned that the logos do not display on mobile. It's the same pattern as on the homepage where we hide images once the display hits 990px.

**Comment by tiyiprh** [comment]
So sorry - I missed that comment!
Hmm this is what it looks like when I open the page now. Looks like the page shrunk:
IMG_8284

**Comment by oraNod** [comment]
@tiyiprh Sorry for making some silly mistakes here and wasting your time. Great reviews though! Think I've got my act together now and fingers crossed it should be good to go now.

**Comment by tiyiprh** [comment]
@oraNod Not at all! You're doing all the hard stuff! It looks great though - thank you for making the changes and bearing with all the nitpicks!!

**Review by tiyiprh — APPROVED** [review]

**Pull request merged**
