### PR TITLE
Events graphics

### PR DESCRIPTION
**Pull request by oraNod**
issue #193 

This PR adds generic / reusable graphics in svg format for Ansible community events. New graphics are a bit smaller so take up less room on the homepage and can scale better without getting constrained like png format. Also makes some minor changes to the event layout.

### CODE REVIEW

**Comment by cybette** [comment]
Looks great @oraNod ! 

The visuals are really cool. For the text, can we use a Sans Serif typeface, e.g. Open Sans, instead of a serifed one?

**Comment by oraNod** [comment]
> Looks great @oraNod !
> 
> The visuals are really cool. For the text, can we use a Sans Serif typeface, e.g. Open Sans, instead of a serifed one?

@cybette Yeah let's do that. I went with the Red Hat font to try and be consistent but agree with the Open Sans suggestion. I was discussing that in issue #204

**Comment by oraNod** [comment]
@cybette The preview build should be using open sans now. And here is a screengrab of the meetup graphic:

image

**Comment by oraNod** [comment]
I also removed the tooltip from the events images similar to https://github.com/ansible-community/community-website/pull/212

**Review by cybette — APPROVED** [review]
LGTM, thanks!

**Comment by oraNod** [comment]
and one final push to update the events so it looks current for the bullhorn announcement and forum post later today.

**Comment by tiyiprh** [comment]
Images look great! Just to confirm, are we changing the font just for this area while the rest of the website uses the RH font family?

**Comment by tiyiprh** [comment]
Some minor updates:
- Based on the number of events we want to show, we should follow a similar format to the blogs section in which there is a fixed width/height for each element of the post based off the longest one and each element of the event should line up horizontally to each other
- The layout of each event should be: Image, title, description, date and location
- Only the event title should be clickable to take the user to the event details page (not the image or description, etc)

From current implementation:
- The area of the Nerdearla image should match the Ansible Contributor Summit so the image should either increase or be centered to have the same width/height
- The title should be under the image and be horizontally lined up together and have a fixed width/height
- The description should have a fixed width/height and be horizontally lined up together
- The date and location should be horizontally lined up together

**Pull request merged**
