### PR TITLE
fix subscribe bull

### LINKED ISSUE #382: Updates to "Subscribe" section
Is there any way to increase the size of the bull just a bit and lessen the spacing between the bull and text?

### PR DESCRIPTION
**Pull request by oraNod**
Resolves #382

### CODE REVIEW

**Comment by tiyiprh** [comment]
This looks a lot better to me! Sorry for the nitpick but would it be possible to make that section a bit shorter by removing some padding from the top and bottom of the section? It should be about the same height as the bull. Here is an example from the mockup.
Screenshot 2024-03-05 at 9 23 42 AM

**Comment by tiyiprh** [comment]
@oraNod I think I see what you mean about the padding when it reduces in size. I'm ok with what you had earlier if that helps avoid adding a new global style and keep it consistent across the various sizes.

**Comment by oraNod** [comment]
Thanks @tiyiprh I think it's better to try and keep it consistent here. I agree that the mockup looks nicer but it gets complicated once you start resizing and all that. I've dropped that last commit if you could look again. Cheers.

**Review by tiyiprh — APPROVED** [review]
LGTM!

**Pull request merged**
