### PR TITLE
Change automate band to ansible

### PR DESCRIPTION
**Pull request by oraNod**
* Rename automate band resources to ansible.
* Add black ansible community logo to band.

### CODE REVIEW

**Comment by oraNod** [comment]
I think this makes the "What is Ansible" band a little more filled out since we restricted text width to 80 characters. The black community logo pairs nicely with the black anchor hover in https://github.com/ansible-community/community-website/pull/258

It is also consistent with the bullhorn and contribute bands that include text and images in 8 column / 4 column layouts.

I didn't anchor the logo. It is purely decorative but has sufficient alt text. We can always point to a url somewhere but I don't really think we need to in this case.

**Review by cybette — APPROVED** [review]
This is great, I was wondering about the space, this would work nicely!

**Comment by oraNod** [comment]
> This is great, I was wondering about the space, this would work nicely!

Thanks, @cybette I've noticed there is some discussion with RH counterparts next week to possibly include additional text in this section. Might as well discuss that a bit here.

In my opinion the content that has been proposed is a better fit for a page dedicated to comparison and understanding between RH customers and community users. I believe that content already exists so there is no need to duplicate it here.

This section aims to provide something that we have consistently heard from the community, at Fosdem, in documentation issues, in Reddit threads, and so on. We need a place that succinctly answers the basic question, What is Ansible?

From there we can be find ways to guide users towards resources like comparison pages and so on. But my strong opinion here is that adding text related to the platform, while helpful for some, is more likely to add complexity and interfere with fulfilling a basic need in the community. It's a hill I'm ready to die on, as the saying goes.

**Comment by GregSutcliffe** [comment]
Do like!

**Comment by tiyiprh** [comment]
For this section, we were considering what to add to the white space as well. We found an illustration that shows collaboration that we thought would fit and go well with the rest of the images/logos we have on the homepage. Let me know what you all think of this!
Screenshot 2023-10-06 at 10 25 21 AM

Here is the SVG. We changed the shirt colors to match the Ansible cyan and coral.
undraw_engineering_team_a7n2

**Comment by oraNod** [comment]
Oh, thanks a mill @tiyiprh I'll send a PR with that illustration and we can compare and get some thoughts. I was sort of keen to merge the other changes and fill the whitespace.

**Pull request merged**
