### PR TITLE
Design feedback on fonts and banner

### PR DESCRIPTION
**Pull request by oraNod**
Fixes issue #159 

- Use Red Hat display as the font family globally.
- Adjust font weight on main banner content.
- Add tooltips to install and get started buttons.
- Move "Install by copying" text to tooltip.
- Add popup to make it clear when text is copied.
- Add right arrows to platform learn more in banner.
- Use fa right arrow instead of circle right arrow.
- Avoid increasing space between buttons when resizing page.

### CODE REVIEW

**Comment by oraNod** [comment]
@tiyiprh Please take a quick look at the changes here too. I'd particularly appreciate feedback on the "Copied" popup for the pip install Ansible button. Thank you!

**Comment by oraNod** [comment]
@tiyiprh I've made some more changes to the "pip install ansible" clipboard. I tried to make it more PatternFly-like and am not opposed to using react but if we decide to go that route, it needs to happen in a separate PR after some wider discussion. For now I like to think the latest changes are reasonable.

Part of the issue I think we're having - and it seems to relate to the bullito scaling issue - is that there are a few different components in the main banner row that are all squishing together and competing for space.

To make things a bit easier to deal with I removed that "fa rocket" from the getting started button on the banner and the "Why Ansible" section to save a bit of space. It also looks a little less visually cluttered now with one less icon in the banner. However I did keep the rocket in the Getting Started button in the menu. It sort of gives that section a bit of "flair" although I'm happy to remove it there too if you think that's best.

I put the "Ansible latest version and copy the command" text inside the button to replace the "pip install ansible" text, which really seemed a bit redundant with the "copy command" text. Anyway that whole thing is now a button and I think it works nicely.

Thanks!

**Comment by oraNod** [comment]
@tiyiprh I see the success message covers the "Ansible 7" text on the preview build. Perhaps we can merge as-is and break that out into a separate issue for the hackathon?

**Comment by oraNod** [comment]
Hmm. OK, I made a slight adjustment and the popup text looks better now and isn't hiding any text on the preview. I'd still like to have someone look at refining this in the hackathon though.

**Comment by tiyiprh** [comment]
@oraNod I think for consistency, we can remove the rocket in the button on the masthead since we are removing it from the other sections.

For the pip command, do we need the additional text describing that Ansible 7 is available? I'm wondering if it would just make sense to keep it as a button and instead say "Copy pip install Ansible?" I feel like that tells the user what the button will do and how to interact with it. Then we can have a tooltip on hover with the additional sentence to provide context. What do you think?
Screenshot 2023-09-22 at 11 13 51 AM

**Comment by GregSutcliffe** [comment]
I'm obviously a bit behind, so this might just be work-in-progress but I really don't like the install command button look right now.

image image

The simple console-font click-to-copy-the-command (left) is pretty standard and I think the way the preview looks right now (right) is more confusing.

**Comment by oraNod** [comment]
@tiyiprh I've removed the rocket icon in the nav button as well.

For the pip command, I think my previous idea isn't so great. It's a button that doesn't really look like a button so that's probably an accessibility concern (WCAG2.1 presentation).

I do like the idea of putting the text in the tooltip as it saves a bit of "real estate" on the banner band and looks a lot cleaner. We can probably also just say "latest version of Ansible" rather than the actual version, especially if it is in the tooltip.

On the button itself I feel like the convention nowadays is to use the clipboard icon to indicate a copy-able block of text. "Copy pip install ansible" looks pretty weird to me. I also think the clipboard icon is more universally understood than the word "copy".

I've made some additional changes, please take a look. Also, what do you think about the colours? Should we use cyan background / white text on hover? Or should the colours not change on hover?

**Comment by oraNod** [comment]
@tiyiprh Also I reduced the text in the clipboard success message and moved it so it pops up to the right of the button. It would be a nightmare to have to adjust the absolute positioning on the page when it resizes. And it's an accessibility concern if the pop up obscures text so we need to put that somewhere it will reliably display, won't interfere with other text, and won't start pushing other elements around when the page resizes.

I looked at some other examples on the web - like Mozilla pages - and the word "Copied!" seems to be widely used.

We could start using PatternFly / React to make this better/fancier but that's definitely a follow up.

**Comment by oraNod** [comment]
> I'm obviously a bit behind, so this might just be work-in-progress but I really don't like the install command button look right now.
> 
> image image
> 
> The simple console-font click-to-copy-the-command (left) is pretty standard and I think the way the preview looks right now (right) is more confusing.

@GregSutcliffe Thanks for looking. I just pushed some changes at the same time as your comment so the button should be back to normal now.

An alternative here might just be to turn this into a regular "Install Ansible" that takes you to [PiPy](https://pypi.org/project/ansible/) and users can do the "pip install ansible" copy pasta there.

**Comment by GregSutcliffe** [comment]
> button should be back to normal now.

Not quite, according to the RTD preview:

image 
image

i.e no border now - not sure if that's intentional?

>that takes you to [PiPy](https://pypi.org/project/ansible/) and users can do the "pip install ansible" copy pasta there

Do we want to move people away from the site? Selfishly, I'd rather not take them to PyPi if we don't have to ;)

**Comment by oraNod** [comment]
> > button should be back to normal now.
> 
> Not quite, according to the RTD preview:
> 
> image image
> 
> i.e no border now - not sure if that's intentional?
> 
> > that takes you to [PiPy](https://pypi.org/project/ansible/) and users can do the "pip install ansible" copy pasta there
> 
> Do we want to move people away from the site? Selfishly, I'd rather not take them to PyPi if we don't have to ;)

Check again. Sometimes it takes RTD a while to load all the styling. This is what I see now:

image

**Comment by oraNod** [comment]
@GregSutcliffe I also agree about not taking users away from the site. (target=_blank) should help there but still. Anyway it was just a suggestion and maybe something we should consider if the javascript bits here just give us too much headache. I think it's fine now but wanted to put that suggestion out there for consideration.

**Comment by GregSutcliffe** [comment]
Ah yes, it's there now. Thanks for the RTD tip, I'll keep that in mind in the future.

**Comment by GregSutcliffe** [comment]
Thanks @oraNod

**Comment by tiyiprh** [comment]
> @tiyiprh Also I reduced the text in the clipboard success message and moved it so it pops up to the right of the button. It would be a nightmare to have to adjust the absolute positioning on the page when it resizes. And it's an accessibility concern if the pop up obscures text so we need to put that somewhere it will reliably display, won't interfere with other text, and won't start pushing other elements around when the page resizes.
> 
> I looked at some other examples on the web - like Mozilla pages - and the word "Copied!" seems to be widely used.
> 
> We could start using PatternFly / React to make this better/fancier but that's definitely a follow up.

I think changing it back to what we had with the copy icon is fine. Regarding the tooltip, since we're not using Patternfly it appears as a tooltip that is part of the web vs on the UI correct? Or is there any way to add it to the UI without using Patternfly?

**Comment by oraNod** [comment]
> > @tiyiprh Also I reduced the text in the clipboard success message and moved it so it pops up to the right of the button. It would be a nightmare to have to adjust the absolute positioning on the page when it resizes. And it's an accessibility concern if the pop up obscures text so we need to put that somewhere it will reliably display, won't interfere with other text, and won't start pushing other elements around when the page resizes.
> > I looked at some other examples on the web - like Mozilla pages - and the word "Copied!" seems to be widely used.
> > We could start using PatternFly / React to make this better/fancier but that's definitely a follow up.
> 
> I think changing it back to what we had with the copy icon is fine. Regarding the tooltip, since we're not using Patternfly it appears as a tooltip that is part of the web vs on the UI correct? Or is there any way to add it to the UI without using Patternfly?

@tiyiprh Hey, I'm not really sure what you mean here to be honest. Could you please maybe open an issue and describe the behaviour / style we should aim for with the tooltips? We can try and style tooltips so they are similar to Patternfly (https://www.w3schools.com/css/css_tooltip.asp) I can take a look and follow up with the issue. Thanks!

**Comment by tiyiprh** [comment]
@oraNod Sorry, I wasn't very clear. I was trying to understand if the current implementation was a default browser generated tooltip vs one we created. I think we'd want to use the CSS tooltips shown in the link you sent. I think the ones with the arrow on the tooltip should be the one to use as it is similar to the PF one.

**Comment by oraNod** [comment]
No worries @tiyiprh Yes, we're just using whatever the browser sets with tooltips. Would you mind creating an issue for that please and I'll look into it?

**Pull request merged**
