### PR TITLE
Updates to the ecosystem page

### LINKED ISSUE #376: Updates to Ecosystem landing page
From the "View more" on the ecosystem section on the landing page and the "Ansible ecosystem" from the Resources dropdown, the user should land on the Ecosystem landing page. To be consistent with the look and feel of the ecosystem cards from the landing page, proposing some updates.

The cards should be the same kind of cards from the landing page with a max height of the project that has the most links. Each project should also have the logo. We may need to create some more logos or placeholders for project that do not have one.

The spacing between the cards and rounded corners for this and the Ansible community training should be the same if possible.

Ansible Ecosystem

### PR DESCRIPTION
**Pull request by oraNod**
Resolves  #376

### CODE REVIEW

**Comment by oraNod** [comment]
@tiyiprh Please take a look and let me know what you think: https://ansible-community-website--420.org.readthedocs.build/ecosystem/#

I didn't include the right arrow fa icon in the anchors. That made the cards a little too busy I think. I guess we could add them back and see if you're curious how it turns out.

**Comment by oraNod** [comment]
Yeah I just played around with adding the right arrow in just to see. Not only does it make the page seem a little busy we're going to encounter the situation where the arrow gets orphaned below the anchor text like this:

image

This happens because the anchor text wraps when it hits a certain point. We could set the style to "nowrap" but that causes overflow with the logo and the description when the page resizes.

**Comment by tiyiprh** [comment]
@oraNod Looking good! 
Just a few things that still need some updating:
1. The header needs to be changed to match the mockup (don't need the logo)
2. There should be a bit more padding between the cards
3. There should be more padding on all sides of the card. It should match the padding of the ecosystem cards on the home page.

**Comment by tiyiprh** [comment]
@oraNod Sorry didn't catch this earlier. But we do have a logo for Galaxy NG: https://github.com/ansible/logos/blob/main/galaxy/galaxy-logo-ansibull.svg

**Comment by oraNod** [comment]
@tiyiprh no worries. thanks for catching that galaxy logo. I've made a few more changes as you suggested. please take another look.

**Comment by tiyiprh** [comment]
Awesome, thanks!
Is there anyway to add some more padding on all sides of the cards to match more like the cards on the home page?

This is the ecosystem card on the home page
Screenshot 2024-02-13 at 12 28 14 PM

This is the card on the ecosystem page. It looks a little squished.
Screenshot 2024-02-13 at 12 28 03 PM

**Comment by tiyiprh** [comment]
@oraNod Thanks for taking the time to make the updates and explain! I think it looks great!! Just a few things:
- I noticed that the EDA logo on the homepage now looks kind of cut off
Screenshot 2024-02-14 at 9 33 12 AM

- How are the logos implemented? Do they all fit into some kind of bounding box to maintain a similar size?

**Comment by oraNod** [comment]
@tiyiprh Could it be that it's a caching issue? I noticed that with the EDA logo before but it shouldn't be doing that. Here's what I see:

image

**Comment by tiyiprh** [comment]
@oraNod The logo on the ecosystem page looks fine! I was just looking at other areas of the website with this build and noticed that on the homepage in the ecosystem section the logo was a bit cut off

**Comment by oraNod** [comment]
bah. I see what you mean now. doh!

**Comment by oraNod** [comment]
@tiyiprh Thanks for catching that one. I've updated the homepage logos to be the same as the ecosystem page. That seems to fix it. Let me know what you think please.

**Review by tiyiprh — APPROVED** [review]
Awesome!! Thank you!

**Pull request merged**
