### PR TITLE
Ansible automation: Improve the wording on the homepage

### PR DESCRIPTION
**Pull request by oraNod**
Fixes issue #101

### CODE REVIEW

**Comment by tiyiprh** [comment]
Hi @oraNod this section looks good to me so far! I'd like to ask @kaedward to take a look as well to provide any feedback: https://ansible-community-website--251.org.readthedocs.build/en/251/

I was curious as to the section title change. I kind of like "What is Ansible?" like Will suggested in #101

**Comment by oraNod** [comment]
Thanks @tiyiprh Yeah, silly me for changing that. "What is Ansible?" is better.

BTW, I found the source for the original text: https://www.ansible.com/overview/it-automation

**Comment by kaedward** [comment]
Thanks @tiyiprh! The content looks great :-)

**Comment by oraNod** [comment]
Thanks everyone!

**Pull request merged**
