### PR TITLE
Open navbar items in new tab 

### LINKED ISSUE #60: target=_blank for nav bar items
Don't direct users away from the site when they click on items in the nav bar.

### PR DESCRIPTION
**Pull request by oraNod**
Fixes #60

### CODE REVIEW

**Comment by oraNod** [comment]
Only nit with this PR is that it causes the Events to open in a new tab, which we might want to load on the same page since it's not taking us away from the site.

**Review by maxamillion — DISMISSED** [review]
LGTM

**Review by vidyanambiar — COMMENTED** [review]
I'd recommend opening a new tab only for nav items that open up an external URL. For a nav item like `Events` which opens up Community Events within the website, it would be good to open it up in the same tab. 
nvm! @oraNod  I just noticed that you already discussed this point above!

**Comment by GregSutcliffe** [comment]
@oraNod Actually this seems to work:
```diff
--- a/themes/ansible-community/templates/base_helper.tmpl
+++ b/themes/ansible-community/templates/base_helper.tmpl
@@ -156,8 +156,10 @@ lang="{{ lang }}">
         {% else %}
             {% if rel_link(permalink, url) == "#" %}
                 <li class="nav-item active"><a href="{{ permalink }}" class="nav-link nav-link-color">{{ text }} <span class="sr-only">{{ messages("(active)", lang) }}</span></a>
-            {% else %}
+            {% elif url.startswith("https://")  %}
                 <li class="nav-item"><a href="{{ url }}" target="_blank" class="nav-link nav-link-color">{{ text }}</a>
+            {% else %}
+                <li class="nav-item"><a href="{{ url }}" class="nav-link nav-link-color">{{ text }}</a>
             {% endif %}
         {% endif %}
     {% endfor %}
```

**Review by cybette — APPROVED** [review]
LGTM!

**Comment by GregSutcliffe** [comment]
Thanks @oraNod!

**Pull request merged**
