### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Spredzy**

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM

**Comment by GregSutcliffe** [comment]
Agree with CC in principle, this repo is going to be content-focused, so a CC license is probably the way to go.

However, I agree with @cybette - https://choosealicense.com/licenses/cc-by-sa-4.0/ is probably the right one. Would like a comment from @anweshadas or @Andersson007 too.

**Comment by Spredzy** [comment]
I created https://github.com/ansible-community/community-website/pull/2 if we want to go with the other one. I created that PR from Github License option directly, cc-by-sa.4.0 wasn't part of it.

Feel free to close that one and merge the other if appropriate.

**Comment by cybette** [comment]
Pending outcome of https://github.com/ansible-community/community-website/issues/3

**Review by GregSutcliffe — COMMENTED** [review]
Looks like we're settling on CCBYSA 4.0 so :-1: in favour of #2

**Comment by cybette** [comment]
Going with CC-BY-SA 4.0, closing this.

**Pull request closed without merging**
