### PR TITLE
Anchor improvements

### PR DESCRIPTION
**Pull request by oraNod**
Fixes issue #252, simplifies scss and templates, ensures all anchors on the homepage open in a new tab/window.

### CODE REVIEW

**Comment by oraNod** [comment]
@tiyiprh Please take a look and let me know your thoughts on the hover stuff. Thanks.

**Comment by tiyiprh** [comment]
@oraNod Looks like the links open in a new tab!

**Comment by oraNod** [comment]
@tiyiprh Hmm. Yeah I suppose we should only open external links in a new tab. I'll fix that then merge. Thanks for spotting it.

**Comment by tiyiprh** [comment]
@oraNod Oh sorry! I thought all the links on the homepage were supposed to open to a new tab, so I was just confirming with your original comment that that was the case. What do you mean only external links would open in a new tab?

**Comment by oraNod** [comment]
@tiyiprh By external links I mean any url under a different domain. Maybe for the blog links we should have them open in the same window?

**Review by tiyiprh — APPROVED** [review]
@oraNod I agree with you that external links should open in a new tab and internal links like blogs should open in the same window.

**Comment by oraNod** [comment]
Thanks @tiyiprh

**Pull request merged**
