### PR TITLE
Check for spelling and wording issues

### PR DESCRIPTION
**Pull request by oraNod**
Issue #96 

This PR adds a codespell check to ci that will detect spelling mistakes and potentially offensive or inappropriate language. Additionally this PR introduces a project toml and noxfile that we can reuse for future configuration.

### CODE REVIEW

**Comment by oraNod** [comment]
@GregSutcliffe Note that I put this into two commits. One to add the codespell tooling and another to fix common spelling mistakes so ci will pass. I thought it would be sensible to keep these in two separate commits.

**Comment by oraNod** [comment]
You can also see an example failure here: https://github.com/oraNod/community-website/actions/runs/6198391668

**Comment by GregSutcliffe** [comment]
Apart from showing up how atrocious my typing is when I'm in the flow (which is clearly fine), I have reservations about this, primarily two:
- How well is this going to handle posts involving other languages? Is it going to trip up on new project names or technologies? In general, is it going to annoy people more than it helps?
- Editing the Bullhorn is a no-no in my opinion, as that's *meant* to be what the user posted to the channel. I Know @cybette does some editing to arrange the pieces and fix known issues (broken URLs etc) but largely it should be what was written, warts'n'all.

To that end, I don't think I can +1 this without more input. @cybette thoughts?

**Comment by oraNod** [comment]
@GregSutcliffe Thanks for the feedback. I get that editing the bullhorn is contentious but if we want to spell check the blog we'll need to fix the old posts or ci will always fail. Should we ignore the blogs and spell check only the site? Maybe we can ignore bullhorn posts.

We can always configure codespell to use another dictionary and add specific words to the allow list if it picks up something odd.

**Comment by oraNod** [comment]
@GregSutcliffe Looks like we can skip the contents of "posts/bullhorn". I'm not sure how annoying this will be for people but, in general, I think a spell check is a good thing for quality. Maybe we want to tone it down and skip all blog posts but, again, I feel like it would be useful there. Surely we'll have all blog posts reviewed before merge anyway, which should include a spelling check.

**Comment by GregSutcliffe** [comment]
I agree with **something** in this line, yes. Just trying to anticipate and get the balance right, and for that we need more voices. In particular I wouldn't deviate from the **published** version of the Bullhorn - for better or worse that *is* what we put out there. Once the new editions start coming through here... well that's up to @cybette

**Comment by oraNod** [comment]
@GregSutcliffe How about we skip the posts entirely for the moment and spell check the homepage (and content of "pages")? We can always revisit and enable this check for blogs if we think it will be useful there. I guess blogs might be a bit less strict and we can rely on manual reviews there. I def don't want to see any spelling issues on the homepage.

Another good thing about the codespell utility is that it will also catch profanity and problematic, non-inclusive language. Not that I expect to ever encounter a PR with coarse language in it but I do feel like having a mandatory check is another layer of quality / trust that will demonstrate the "safe pair of hands" thing.

**Comment by cybette** [comment]
I agree we should leave out bullhorn posts, and maybe blog posts in general. I do fix some obvious typos but I leave things like the differences between UK and US spelling alone, to reflect the author's language and way of writing. In addition there are many project/collection/module/variable names to account for, not to mention nicknames of people submitting news items.

For the homepage, yes, I think the spell check will have much more value there.

**Comment by oraNod** [comment]
I'm going ahead with this given that we're only checking the homepage. We can revisit blogs. Thanks!

**Comment by GregSutcliffe** [comment]
I'm late to the party here, but FWIW I support this being enabled on the homepage!

**Pull request merged**
