### PR TITLE
Anchor colour

### PR DESCRIPTION
**Pull request by oraNod**
issue #261

### CODE REVIEW

**Comment by oraNod** [comment]
Actually I've reworked it so that only certain anchors on the homepage change colour and everything else - mainly the blogs - use the accessible default.

**Comment by oraNod** [comment]
@tiyiprh Could you please take a look here too and advise on the anchor colour. It needs to pass the Link Contrast Check.

Here is what is in the current PR: https://webaim.org/resources/linkcontrastchecker/?fcolor=000000&bcolor=FFFFFF&lcolor=3333FF

The link colour I've chosen is `#3333FF` but I'm open to suggestions. It's worth noting that this link colour also applies to blog posts globally, not just on the homepage.

**Comment by tiyiprh** [comment]
@oraNod Per my comment in #261 we would like to change the link color to #0066CC and have it turn to navy on hover and be underlined. Let me know what you think!

**Comment by oraNod** [comment]
@tiyiprh I don't think we're going to be able to change colour on hover. The community navy fails the contrast check for links: https://webaim.org/resources/linkcontrastchecker/?fcolor=000000&bcolor=FFFFFF&lcolor=102441

**Pull request merged**
