### PR TITLE
Design feedback on icons and colors

### PR DESCRIPTION
**Pull request by oraNod**
Fixes issue #160 

- Adds cyan icons for menu bar and sections.
- Uses cyan for fa icons in the community band.
- Adds text to each icon in the community band.
- Adds hover to each icon in the community band.
- Changes the button color on bullhorn subscribe.

### CODE REVIEW

**Comment by tiyiprh** [comment]
This looks good so far!

**Comment by oraNod** [comment]
> * **Adds text to each icon in the community band.**
>       Looks good. I would keep the text as RH Display and regular weight.
> 
>     * **Adds hover to each icon in the community band**
>       The hover looks great!! Would it be possible to shrink the icons to about the same size as the icon in each section header (~ 40x40 px)? Would it also be possible to combine the text area as part of the icon so the text area + icon are clickable? This community section doesn't need to be as large and can be a thin section similar to the bullhorn area.

Thanks @tiyiprh 

Text will default to RH display throughout once https://github.com/ansible-community/community-website/pull/168 is merged. I did notice one other place where fonts where we're inheriting `$redhat-text` but I'll fix it.

- Set the font size to 40px to match the icons.
- Put the text in with the anchor so it's clickable too. I also set `text-decoration: none;` so the text area isn't underlined on hover.

**Comment by oraNod** [comment]
> Sorry @oraNod, I have a few more comments on this on the community section!

No need to apologise @tiyiprh These reviews are great and it's nice to be getting into this level of detail.

**Comment by tiyiprh** [comment]
> > * **Adds text to each icon in the community band.**
> >   Looks good. I would keep the text as RH Display and regular weight.
> >   
> >   * **Adds hover to each icon in the community band**
> >     The hover looks great!! Would it be possible to shrink the icons to about the same size as the icon in each section header (~ 40x40 px)? Would it also be possible to combine the text area as part of the icon so the text area + icon are clickable? This community section doesn't need to be as large and can be a thin section similar to the bullhorn area.
> 
> Thanks @tiyiprh
> 
> Text will default to RH display throughout once #168 is merged. That `$redhat-text` family is still getting inherited from the main stylesheet but the other PR fixes it.
> 
> * Set the font size to 40px to match the icons.
> * Put the text in with the anchor so it's clickable too. I also set `text-decoration: none;` so the text area isn't underlined on hover.

Looks great! I wonder if it would make sense to make the text change color on hover too? To make it more like the icon and text are one thing? What do you think?

**Comment by oraNod** [comment]
@tiyiprh I've made another change so the text and the icon both hover together. Since the icon is actually a font - and we need it to be 40px and the text 1rem - I think we'll have to live with the fact that the hovering over the icon changes both icon and text while hovering over the text changes only the text. I don't think it's a huge deal though.

**Comment by oraNod** [comment]
> I see. Sorry if I'm misunderstanding, but what is the reason that happens?

@tiyiprh As it happens the reason was pretty much just me over complicating things. I'm doing a lot of learning as I go here... It should be working as expected now with both the text and the icon hovering together. Thanks again for the review!

**Comment by GregSutcliffe** [comment]
Hover looks right to me now, thanks @oraNod @tiyiprh. Lets keep the momentum going!

**Comment by tiyiprh** [comment]
All good! Just wasn't sure if it was because I don't understand how coding and such works haha but looks good to me! Thanks for making the update!

**Pull request merged**
