### PR TITLE
add technical writer persona

### PR DESCRIPTION
**Pull request by oraNod**
Partially addresses #15 by describing the technical writer persona.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Is this aimed at some of the other pages we have in mind? There's obviously only so much we can do with the front page, so I'm assuming this persona's journey starts off in a very similar way to the existing contributor persona?

**Comment by oraNod** [comment]
@GregSutcliffe Yes this is aimed at the Technical Writer's Toolkit: https://hackmd.io/XmvP5LcbRBSaB6hvmkQfgg

We haven't got to it yet but there could possibly be a "toolkit" section on the homepage where we link to pages for the meetup organizer toolkit and the writer's toolkit.

**Comment by samccann** [comment]
I wonder if we want a separate persona for technical writers vs documentation contributors? I agree with how it's described here - writers may not know Ansible, or be that familiar with git or sphinx/mkdocs etc.

I could see this going one of two ways:
- make this a generic documentation contributor persona - This means we can't assume they know the fundamentals of technical writing and would want to point out style guides etc. But we do tend to assume they either understand git and sphinx/mkdocs or won't need it (using edit on github).
- Keep this as specific to technical writer persona - We can't assume they know git or sphinx/mkdocs, but can assume they understand style guides and how to follow RST or md etc. We would have to give pointers to getting up to speed on git and sphinx etc.

We do have a need for technical writers in that today 99% of all ansible ecosystem docs are written by people who are not technical writers. That said, it's a new persona and we should probably get technical writers to review this. There are a couple we could ask for reviews if we want this as a separate persona.

**Comment by samccann** [comment]
@oraNod saw your comment after I put mine up. I see that documentation toolkit as targeting anyone, not just techwriters so to speak. So if a developer is starting up the Ansible foo project, they can use it to determine how best to build their docs. It can also be used by a technical writer coming into a project to help out. So a dual use.

**Comment by oraNod** [comment]
@samccann Thanks for that. I can update my PR. Do you think the generic docs contributor would be better with your last comment in mind?

**Comment by oraNod** [comment]
@GregSutcliffe Someone expressed interest in contributing in #docs:ansible.com earlier today and I pointed to a bunch of links scattered across docs and repos. It got me thinking about the toolkits. Maybe Discourse is the place for Contributor Toolkits, not the website?

If so, where does this persona belong?

**Comment by cybette** [comment]
> It got me thinking about the toolkits. Maybe Discourse is the place for Contributor Toolkits, not the website?

I've been thinking about this too (more for the meetup organizers toolkit, but can apply to toolkits in general) - I see it as something other meetup organizers / contributors can edit and add their views and experiences to enhance the toolkit. So a wiki-style page rather than a webpage could be more suited. Of course they can also submit PRs to add to the website, but having it on discourse (as wiki) can also encourage discussions about the toolkit(s), which I think was sorely lacking in the previous toolkit on GitHub wiki.

**Comment by cybette** [comment]
Website - informative
Forum - collaborative

And imho toolkits should be collaborative :)

**Comment by oraNod** [comment]
Thank you @cybette agreed. Should I close this PR and the meetup organizer toolkit? Do we even need to define personas for them? Maybe we should have informative links to the discourse toolkits from somewhere on the site?

**Comment by GregSutcliffe** [comment]
Lots of good thoughts here, I especially like @cybette's breakdown of website vs forum usage. I'd add this example from https://meta.discourse.org/c/documentation/10 as a good example of how collaborative-yet-primarily-informative stuff can be shown in Discourse:

image

I think about this a lot, because it blurs the lines between the website and the forum - those topics are undeniably a docs/howto/help resource that is consumed by many, but the discussion/feedback on the topics is undoubtedly useful to (but probably happens in lieu of discussion on Github, which is where *we* might look for it). It's non-trivial to solve, and I suspect it's something we'll revisit as the forum takes shape.

**Comment by samccann** [comment]
This feels like an odd place to discuss this but since the history is here, I'll continue - It feels to me like toolkits are less collaborative, more informative. Thinking about the proposed documentation writers toolkit - i can say anyone using it or considering making changes to it has to be git saavy. I can also say it won't change that much. So to me, that particular toolkit should live in a website/docsite somewhere.

For the meetup toolkit - I have less experience so I don't know if people will be actively editing it. But I can see having it in git could be a barrier to those wanting to make changes.  Even simple edit on github functionality requires a github ID. Do meetup organizers typically already work in github? If so, then keeping the source in github makes sense to me.
Note there is no 'issue' or 'pr' functionality in discourse afaik. So yes it can be easier to edit for rapid iterations,  but it's harder to track when someone is just asking us to make a change vs doing it themselves.

**Comment by cybette** [comment]
I can't speak for the writers toolkit, but for the meetup toolkit, there are a number of organizers who use GitHub but probably a fair bit who don't. Also I still think meetup toolkit is collaborative. We (a few people in the community team) can't come up with everything (or even most things) the organizers across the globe needs. I can already see the Benelux organizers sharing how they handle no-shows, different groups suggesting locations that works in some regions but not others, people adding info on how they handle swag that they procure themselves (Ansible beers! Not endorsed by Red Hat!), live streaming and hybrid meetup setups etc. Just in 2023 alone I have worked with many meetup groups that I think will be able to contribute their experiences to the toolkit. I don't know if ultimately the website is the best place for the toolkit, but in the meantime I firmly believe the forum will be the best place to discuss and iterate on it.

CC @anweshadas

**Comment by oraNod** [comment]
Great discussion here but I think this PR is no longer needed so I'll close it. Thanks everyone.

**Pull request closed without merging**
